name: VelioraSuite
version: 1.2.0
main: id.velioragardens.veliorasuite.VelioraSuite
api-version: '1.21'
author: XandMe
description: Clean modular plugin suite for Veliora Gardens.

softdepend:
  - Vault
  - PlaceholderAPI
  - LuckPerms
  - Essentials
  - EconomyShopGUI
  - RedProtect
  - SkinsRestorer
  - GSit
  - Geyser-Spigot
  - floodgate

commands:
  veliorasuite:
    description: Main command for VelioraSuite.
    usage: /veliorasuite
    aliases:
      - vsuite
      - vs
    permission: veliorasuite.admin

  velioraguide:
    description: Open Veliora guide pages.
    usage: /velioraguide [page|reload]
    aliases:
      - vguide
    permission: veliorasuite.guide.use

  veliorarules:
    description: Open Veliora rules pages.
    usage: /veliorarules [page]
    aliases:
      - vrules
    permission: veliorasuite.guide.use

  velioraproduct:
    description: Open Veliora product pages.
    usage: /velioraproduct [page]
    aliases:
      - vproduct
    permission: veliorasuite.guide.use

  velioraannouncement:
    description: Manage Veliora automatic announcements.
    usage: /velioraannouncement <help|status|list|reload|send>
    aliases:
      - vannounce
      - vann
      - va

  kits:
    description: Open and claim Veliora kits.
    usage: /kits <help|open|list|claim|preview|buy|cooldown|reload>
    aliases:
      - veliorakits
      - vkits

permissions:
  veliorasuite.admin:
    description: Allows access to VelioraSuite admin command.
    default: op

  veliorasuite.bypass:
    description: Allows bypassing VelioraSuite protections.
    default: op

  veliorasuite.guide.use:
    description: Allows players to open Veliora guide pages.
    default: true

  veliorasuite.guide.admin:
    description: Allows admins to reload VelioraGuide.
    default: op

  veliorasuite.announcement.admin:
    description: Allows full access to VelioraAnnouncement.
    default: op

  veliorasuite.announcement.reload:
    description: Allows reloading VelioraAnnouncement.
    default: op

  veliorasuite.announcement.send:
    description: Allows sending manual announcements.
    default: op

  veliorasuite.announcement.status:
    description: Allows viewing VelioraAnnouncement status and list.
    default: op

  veliorasuite.kits.use:
    description: Allows players to use VelioraKits.
    default: true

  veliorasuite.kits.admin:
    description: Allows full access to VelioraKits.
    default: op

  veliorasuite.kits.reload:
    description: Allows reloading VelioraKits.
    default: op

  veliorasuite.kits.bypasscooldown:
    description: Allows bypassing kit cooldown.
    default: op

  veliorasuite.kits.bypassprice:
    description: Allows bypassing kit prices.
    default: op
