name: VelioraSuite
version: 1.2.0
main: id.velioragardens.veliorasuite.VelioraSuite
api-version: '1.21'
author: XandMe
description: Clean modular plugin suite for Veliora Gardens.

softdepend:
  - Vault
  - PlaceholderAPI
  - LuckPerms

commands:
  veliorasuite:
    description: Main command for VelioraSuite.
    usage: /veliorasuite
    aliases:
      - vsuite
      - vs
    permission: veliorasuite.admin

  velioraguide:
    description: Open Veliora guide pages.
    usage: /velioraguide [page|reload]
    aliases:
      - vguide
    permission: veliorasuite.guide.use

  veliorarules:
    description: Open Veliora rules pages.
    usage: /veliorarules [page]
    aliases:
      - vrules
    permission: veliorasuite.guide.use

  velioraproduct:
    description: Open Veliora product pages.
    usage: /velioraproduct [page]
    aliases:
      - vproduct
    permission: veliorasuite.guide.use

  velioraannouncement:
    description: Manage Veliora automatic announcements.
    usage: /velioraannouncement <reload|status|send>
    aliases:
      - vannounce
      - vannounce
    permission: veliorasuite.announcement.admin

permissions:
  veliorasuite.admin:
    description: Allows access to VelioraSuite admin command.
    default: op

  veliorasuite.bypass:
    description: Allows bypassing VelioraSuite protections.
    default: op

  veliorasuite.guide.use:
    description: Allows players to open Veliora guide pages.
    default: true

  veliorasuite.guide.admin:
    description: Allows admins to reload VelioraGuide.
    default: op

  veliorasuite.announcement.admin:
    description: Allows admins to manage VelioraAnnouncement.
    default: op
