package id.velioragardens.veliorasuite.module.guard;

import id.velioragardens.veliorasuite.VelioraSuite;
import id.velioragardens.veliorasuite.api.VelioraModule;
import id.velioragardens.veliorasuite.command.DisabledCommand;
import org.bukkit.*;
import org.bukkit.block.Block;
import org.bukkit.command.*;
import org.bukkit.configuration.ConfigurationSection;
import org.bukkit.configuration.file.YamlConfiguration;
import org.bukkit.entity.*;
import org.bukkit.event.*;
import org.bukkit.event.block.*;
import org.bukkit.event.entity.*;
import org.bukkit.event.inventory.InventoryClickEvent;
import org.bukkit.event.player.*;
import org.bukkit.event.vehicle.VehicleEnterEvent;
import org.bukkit.inventory.*;
import org.bukkit.inventory.meta.ItemMeta;
import org.bukkit.persistence.PersistentDataType;
import java.io.*;
import java.util.*;
import java.util.function.Consumer;

/** Full-height protection for official server areas; separate from player claims. */
public final class GuardClaimModule implements VelioraModule, Listener, CommandExecutor, TabCompleter {
 private static final List<String> F=List.of("break","place","drop-items","pvp","chest","door","iron-door","trapdoor","lever","button","allow-fly","use-potions","spawn","passives","monster-damage","fire","creeper","tnt","ice-form","ice-melt","invincible","minecart","boat","teleport");
 private final VelioraSuite plugin; private final Map<String,C> claims=new LinkedHashMap<>(); private final Map<UUID,Location> p1=new HashMap<>(),p2=new HashMap<>(); private final Map<UUID,String> inside=new HashMap<>(); private final NamespacedKey key; private File file; private boolean enabled;
 public GuardClaimModule(VelioraSuite p){plugin=p;key=new NamespacedKey(p,"guard_flag");}
 public String getName(){return "guardclaim";} public void load(){file=new File(plugin.getDataFolder(),"data/guard-claims.yml");loadData();}
 public void enable(){enabled=true;PluginCommand c=plugin.getCommand("vgclaim");if(c!=null){c.setExecutor(this);c.setTabCompleter(this);}Bukkit.getPluginManager().registerEvents(this,plugin);}
 public void disable(){enabled=false;HandlerList.unregisterAll(this);save();PluginCommand c=plugin.getCommand("vgclaim");if(c!=null){DisabledCommand d=new DisabledCommand(plugin,"VelioraGuard");c.setExecutor(d);c.setTabCompleter(d);}}
 public void reload(){save();loadData();} public boolean isEnabled(){return enabled;}
 public boolean onCommand(CommandSender s,Command cmd,String l,String[] a){
  if(!(s instanceof Player p)){s.sendMessage("Command ini hanya untuk player.");return true;}if(!admin(p)){msg(p,"&cKamu tidak punya izin Guard Claim.");return true;}if(a.length==0){help(p);return true;}String x=a[0].toLowerCase();
  if(x.equals("pos1")||x.equals("pos2")){(x.equals("pos1")?p1:p2).put(p.getUniqueId(),p.getLocation());msg(p,"&aPosisi "+(x.equals("pos1")?"1":"2")+" disimpan: &f"+loc(p.getLocation()));return true;}
  if(x.equals("claim")&&a.length>1){String id=safe(a[1]);Location q=p1.get(p.getUniqueId()),r=p2.get(p.getUniqueId());if(id.isBlank()||claims.containsKey(id)){msg(p,"&cID tidak valid atau sudah dipakai.");return true;}if(q==null||r==null||q.getWorld()==null||!q.getWorld().equals(r.getWorld())){msg(p,"&cAtur pos1 dan pos2 di world yang sama dahulu.");return true;}C c=C.make(id,q,r);defaults(c);claims.put(id,c);save();msg(p,"&aClaim &f"+id+" &adibuat dari bawah dunia sampai atas dunia.");return true;}
  if((x.equals("delete")||x.equals("remove"))&&a.length>2&&a[2].equalsIgnoreCase("confirm")){C c=claims.remove(safe(a[1]));if(c==null)msg(p,"&cClaim tidak ditemukan.");else{save();msg(p,"&aClaim &f"+c.id+" &adihapus.");}return true;}
  if(x.equals("flag")&&a.length>1){C c=claims.get(safe(a[1]));if(c==null){msg(p,"&cClaim tidak ditemukan.");return true;}if(a.length==2){gui(p,c);return true;}String f=norm(a[2]);if(f.equals("welcome")||f.equals("welcome-subtitle")){if(a.length<4){msg(p,"&cMasukkan teks.");return true;}c.text.put(f,String.join(" ",Arrays.copyOfRange(a,3,a.length)));save();msg(p,"&aTeks diperbarui.");return true;}if(f.equals("spawn-mobs")){c.mobs=a.length<4?"":clean(String.join(" ",Arrays.copyOfRange(a,3,a.length)));save();msg(p,"&aSpawn mobs: &f"+(c.mobs.isBlank()?"semua hostile":c.mobs));return true;}if(!F.contains(f)||a.length<4){msg(p,"&cGunakan /vgclaim flag <id> <flag> <true|false>.");return true;}Boolean v=bool(a[3]);if(v==null){msg(p,"&cGunakan true atau false.");return true;}c.flags.put(f,v);save();msg(p,"&aFlag &f"+f+" &adiubah ke "+on(v)+"&a.");return true;}
  if(x.equals("flags")){C c=a.length>1?claims.get(safe(a[1])):at(p.getLocation());if(c==null){msg(p,"&cBerdiri di dalam claim, atau gunakan /vgclaim flags <id>.");return true;}gui(p,c,0);return true;}if(x.equals("list")){msg(p,claims.isEmpty()?"&7Belum ada claim.":"&bClaim: &f"+String.join(", ",claims.keySet()));return true;}if(x.equals("info")&&a.length>1){info(p,claims.get(safe(a[1])));return true;}if(x.equals("reload")){reload();msg(p,"&aGuard Claim dimuat ulang.");return true;}help(p);return true;
 }
 @EventHandler(priority=EventPriority.HIGHEST,ignoreCancelled=true)public void br(BlockBreakEvent e){deny(e.getPlayer(),e.getBlock().getLocation(),"break",e::setCancelled,"menghancurkan blok");}
 @EventHandler(priority=EventPriority.HIGHEST,ignoreCancelled=true)public void pl(BlockPlaceEvent e){deny(e.getPlayer(),e.getBlockPlaced().getLocation(),"place",e::setCancelled,"menaruh blok");}
 @EventHandler(priority=EventPriority.HIGHEST,ignoreCancelled=true)public void drop(PlayerDropItemEvent e){deny(e.getPlayer(),e.getPlayer().getLocation(),"drop-items",e::setCancelled,"menjatuhkan item");}
 @EventHandler(priority=EventPriority.HIGHEST,ignoreCancelled=true)public void inter(PlayerInteractEvent e){if(e.getClickedBlock()==null)return;String f=interFlag(e.getClickedBlock());if(f!=null)deny(e.getPlayer(),e.getClickedBlock().getLocation(),f,e::setCancelled,"menggunakan blok ini");if(e.getItem()!=null){String n=e.getItem().getType().name();if(n.contains("BOAT")||n.contains("RAFT"))deny(e.getPlayer(),e.getClickedBlock().getLocation(),"boat",e::setCancelled,"menaruh perahu");if(n.contains("MINECART"))deny(e.getPlayer(),e.getClickedBlock().getLocation(),"minecart",e::setCancelled,"menaruh minecart");}}
 @EventHandler(priority=EventPriority.HIGHEST,ignoreCancelled=true)public void damage(EntityDamageByEntityEvent e){Player p=attacker(e.getDamager());if(p!=null&&e.getEntity() instanceof Player v)deny(p,v.getLocation(),"pvp",e::setCancelled,"PvP");if(p!=null&&passive(e.getEntity()))deny(p,e.getEntity().getLocation(),"passives",e::setCancelled,"menyerang hewan atau NPC");if(e.getDamager() instanceof Monster&&e.getEntity() instanceof Player v){C c=at(v.getLocation());if(c!=null&&!c.flag("monster-damage"))e.setCancelled(true);}}
 @EventHandler(priority=EventPriority.HIGHEST,ignoreCancelled=true)public void potion(PotionSplashEvent e){if(!(e.getPotion().getShooter() instanceof Player p))return;for(LivingEntity t:e.getAffectedEntities()){C c=at(t.getLocation());if(c!=null&&!c.flag("use-potions")&&!bypass(p)){e.setCancelled(true);msg(p,"&cRamuan tidak dapat digunakan di area ini.");return;}}}
 @EventHandler(priority=EventPriority.HIGHEST,ignoreCancelled=true)public void spawn(CreatureSpawnEvent e){if(e.getSpawnReason()==CreatureSpawnEvent.SpawnReason.CUSTOM)return;C c=at(e.getLocation());if(c==null)return;if(monster(e.getEntity())){if(!c.flag("spawn")||(!c.mobs.isBlank()&&!Arrays.asList(c.mobs.split(",")).contains(e.getEntityType().name().toLowerCase())))e.setCancelled(true);}else if(passive(e.getEntity())&&!c.flag("passives"))e.setCancelled(true);}
 @EventHandler(priority=EventPriority.HIGHEST,ignoreCancelled=true)public void expl(EntityExplodeEvent e){C c=at(e.getLocation());if(c!=null&&!c.flag(e.getEntity() instanceof Creeper?"creeper":"tnt"))e.blockList().clear();}
 @EventHandler(priority=EventPriority.HIGHEST,ignoreCancelled=true)public void expl2(BlockExplodeEvent e){C c=at(e.getBlock().getLocation());if(c!=null&&!c.flag("tnt"))e.blockList().clear();}
 @EventHandler(priority=EventPriority.HIGHEST,ignoreCancelled=true)public void fire(BlockIgniteEvent e){C c=at(e.getBlock().getLocation());if(c!=null&&!c.flag("fire"))e.setCancelled(true);}
 @EventHandler(priority=EventPriority.HIGHEST,ignoreCancelled=true)public void spread(BlockSpreadEvent e){C c=at(e.getBlock().getLocation());if(c!=null&&!c.flag("fire")&&e.getNewState().getType()==Material.FIRE)e.setCancelled(true);}
 @EventHandler(priority=EventPriority.HIGHEST,ignoreCancelled=true)public void form(BlockFormEvent e){C c=at(e.getBlock().getLocation());if(c!=null&&!c.flag("ice-form")&&e.getNewState().getType()==Material.ICE)e.setCancelled(true);}
 @EventHandler(priority=EventPriority.HIGHEST,ignoreCancelled=true)public void melt(BlockFadeEvent e){C c=at(e.getBlock().getLocation());if(c!=null&&!c.flag("ice-melt"))e.setCancelled(true);}
 @EventHandler(priority=EventPriority.HIGHEST,ignoreCancelled=true)public void inv(EntityDamageEvent e){if(e.getEntity() instanceof Player p){C c=at(p.getLocation());if(c!=null&&c.flag("invincible"))e.setCancelled(true);}}
 @EventHandler(priority=EventPriority.HIGHEST,ignoreCancelled=true)public void vehicle(VehicleEnterEvent e){if(e.getEntered() instanceof Player p){String f=e.getVehicle() instanceof Boat?"boat":e.getVehicle() instanceof Minecart?"minecart":null;if(f!=null)deny(p,e.getVehicle().getLocation(),f,e::setCancelled,"menggunakan kendaraan");}}
 @EventHandler(priority=EventPriority.HIGHEST,ignoreCancelled=true)public void tp(PlayerTeleportEvent e){if(e.getTo()==null||bypass(e.getPlayer()))return;C c=at(e.getTo());if(c!=null&&!c.flag("teleport")){e.setCancelled(true);msg(e.getPlayer(),"&cTeleport ke area ini dilarang.");}}
 @EventHandler public void move(PlayerMoveEvent e){if(e.getTo()==null||same(e.getFrom(),e.getTo()))return;C c=at(e.getTo());String n=c==null?null:c.id;if(!Objects.equals(inside.get(e.getPlayer().getUniqueId()),n)){if(n==null)inside.remove(e.getPlayer().getUniqueId());else{inside.put(e.getPlayer().getUniqueId(),n);e.getPlayer().sendTitle(col("&a&lWELCOME"),col("&fTO &e"+c.id.toUpperCase(Locale.ROOT)),5,40,10);}}if(c!=null&&!c.flag("allow-fly")&&!bypass(e.getPlayer())&&e.getPlayer().isFlying())e.getPlayer().setFlying(false);}
 @EventHandler public void click(InventoryClickEvent e){if(!(e.getInventory().getHolder() instanceof H h)||!(e.getWhoClicked() instanceof Player p)){return;}e.setCancelled(true);ItemStack i=e.getCurrentItem();if(i==null||!i.hasItemMeta())return;String f=i.getItemMeta().getPersistentDataContainer().get(key,PersistentDataType.STRING);if(f==null)return;if(f.equals("__next")){gui(p,h.c,h.page+1);return;}if(f.equals("__previous")){gui(p,h.c,h.page-1);return;}if(f.equals("__close")){p.closeInventory();return;}if(!F.contains(f))return;h.c.flags.put(f,!h.c.flag(f));save();gui(p,h.c,h.page);}
 private void deny(Player p,Location l,String f,Consumer<Boolean> cancel,String action){C c=at(l);if(c==null||c.flag(f)||bypass(p))return;cancel.accept(true);msg(p,"&cKamu tidak dapat "+action+" di area &f"+c.id+"&c.");}
 private String interFlag(Block b){String n=b.getType().name();if(n.contains("TRAPDOOR"))return "trapdoor";if(n.contains("DOOR"))return n.contains("IRON")?"iron-door":"door";if(n.endsWith("FENCE_GATE"))return "door";if(n.endsWith("LEVER"))return "lever";if(n.endsWith("BUTTON"))return "button";return b.getState() instanceof InventoryHolder||n.equals("CHISELED_BOOKSHELF")?"chest":null;}
 private Player attacker(Entity e){if(e instanceof Player p)return p;if(e instanceof Projectile q&&q.getShooter() instanceof Player p)return p;return null;} private boolean monster(Entity e){return e instanceof Monster||e instanceof Slime||e instanceof Ghast||e instanceof Shulker;}private boolean passive(Entity e){return e instanceof Animals||e instanceof Villager||e instanceof Golem||e instanceof WaterMob||e instanceof Ambient;}
 private C at(Location l){if(l==null||l.getWorld()==null)return null;for(C c:claims.values())if(c.world.equals(l.getWorld().getUID())&&l.getBlockX()>=c.x1&&l.getBlockX()<=c.x2&&l.getBlockZ()>=c.z1&&l.getBlockZ()<=c.z2)return c;return null;} private boolean bypass(Player p){return p.isOp()||p.hasPermission("veliorasuite.guard.bypass")||p.hasPermission("veliorasuite.bypass");}private boolean admin(Player p){return bypass(p)||p.hasPermission("veliorasuite.guard.admin");}
 private void gui(Player p,C c){gui(p,c,0);}private void gui(Player p,C c,int requested){int max=(F.size()+17)/18;int page=Math.max(0,Math.min(max-1,requested));Inventory i=Bukkit.createInventory(new H(c,page),54,col("&2&lGUARD CLAIM &7| &f"+c.id));for(int slot=0;slot<54;slot++)i.setItem(slot,named(Material.GRAY_STAINED_GLASS_PANE," ",List.of()));int start=page*18;for(int n=0;n<18&&start+n<F.size();n++){int row=n/6,col=n%6;i.setItem(10+row*9+col,item(c,F.get(start+n)));}if(page>0)i.setItem(45,control(Material.ARROW,"&eSebelumnya","__previous"));i.setItem(49,named(Material.BOOK,"&bPanduan Flag",List.of("&7Hijau = TRUE / diizinkan","&7Merah = FALSE / dilindungi","&7Klik item untuk mengubah.","&7Halaman "+(page+1)+"/"+max,"&8spawn-mobs dan teks welcome","&8tetap dapat diatur melalui command.")));if(page<max-1)i.setItem(53,control(Material.ARROW,"&eBerikutnya","__next"));i.setItem(48,control(Material.BARRIER,"&cTutup","__close"));p.openInventory(i);}private ItemStack control(Material material,String name,String value){ItemStack i=named(material,name,List.of("&7Klik untuk memilih."));ItemMeta m=i.getItemMeta();m.getPersistentDataContainer().set(key,PersistentDataType.STRING,value);i.setItemMeta(m);return i;}private ItemStack item(C c,String f){boolean on=c.flag(f);String title=f.toUpperCase(Locale.ROOT).replace('-',' ');List<String> lore=new ArrayList<>();lore.add(on?"&a&lON &7- fungsi diizinkan":"&c&lOFF &7- fungsi dilindungi");lore.add("&f"+flagDescription(f));lore.add(on?"&aKlik: ubah menjadi OFF":"&eKlik: ubah menjadi ON");ItemStack i=named(on?Material.LIME_WOOL:Material.RED_WOOL,(on?"&a":"&c")+title,lore);ItemMeta m=i.getItemMeta();m.getPersistentDataContainer().set(key,PersistentDataType.STRING,f);i.setItemMeta(m);return i;}private String flagDescription(String f){return switch(f){case "break"->"Hancurkan blok oleh publik";case "place"->"Pasang blok oleh publik";case "drop-items"->"Buang item di dalam area";case "pvp"->"Serangan antar pemain";case "chest"->"Buka chest dan container";case "door"->"Pintu kayu dan fence gate";case "iron-door"->"Pintu besi";case "trapdoor"->"Trapdoor kayu/besi";case "lever"->"Tuas redstone";case "button"->"Tombol redstone";case "allow-fly"->"Terbang di dalam area";case "use-potions"->"Ramuan splash/lingering";case "spawn"->"Spawn monster alami";case "passives"->"Hewan/NPC publik";case "monster-damage"->"Damage dari monster";case "fire"->"Api dan penyebarannya";case "creeper"->"Ledakan Creeper";case "tnt"->"Ledakan TNT";case "ice-form"->"Air membeku menjadi es";case "ice-melt"->"Es mencair menjadi air";case "invincible"->"Pemain kebal damage";case "minecart"->"Gunakan minecart";case "boat"->"Gunakan atau pasang perahu";case "teleport"->"Teleport masuk ke area";default->"Pengaturan area";};}private ItemStack named(Material m,String n,List<String> l){ItemStack i=new ItemStack(m);ItemMeta x=i.getItemMeta();x.setDisplayName(col(n));x.setLore(l.stream().map(this::col).toList());i.setItemMeta(x);return i;}
 private void defaults(C c){for(String f:F)c.flags.put(f,Set.of("door","allow-fly","spawn","monster-damage","ice-form","ice-melt","minecart","boat","teleport").contains(f));c.text.put("welcome","&aWELCOME");c.text.put("welcome-subtitle","&f"+c.id);}
 private void loadData(){claims.clear();YamlConfiguration y=YamlConfiguration.loadConfiguration(file);ConfigurationSection r=y.getConfigurationSection("claims");if(r==null)return;for(String id:r.getKeys(false))try{String p="claims."+id+".";C c=new C(id,UUID.fromString(y.getString(p+"world")),y.getString(p+"world-name","world"),y.getInt(p+"min-x"),y.getInt(p+"max-x"),y.getInt(p+"min-z"),y.getInt(p+"max-z"));defaults(c);for(String f:F)if(y.contains(p+"flags."+f))c.flags.put(f,y.getBoolean(p+"flags."+f));Map<String,String> old=Map.of("doors","door","iron-doors","iron-door","trapdoors","trapdoor","containers","chest","hostile-spawn","spawn","passive-spawn","passives");for(var q:old.entrySet())if(y.contains(p+"flags."+q.getKey()))c.flags.put(q.getValue(),y.getBoolean(p+"flags."+q.getKey()));if(y.contains(p+"flags.explosions")){boolean v=y.getBoolean(p+"flags.explosions");c.flags.put("creeper",v);c.flags.put("tnt",v);}c.text.put("welcome",y.getString(p+"welcome.title",c.text.get("welcome")));c.text.put("welcome-subtitle",y.getString(p+"welcome.subtitle",c.text.get("welcome-subtitle")));c.mobs=clean(y.getString(p+"spawn-mobs",""));claims.put(id,c);}catch(Exception ex){plugin.getLogger().warning("Guard Claim rusak dilewati: "+id);}}
 private void save(){YamlConfiguration y=new YamlConfiguration();for(C c:claims.values()){String p="claims."+c.id+".";y.set(p+"world",c.world.toString());y.set(p+"world-name",c.worldName);y.set(p+"min-x",c.x1);y.set(p+"max-x",c.x2);y.set(p+"min-z",c.z1);y.set(p+"max-z",c.z2);for(String f:F)y.set(p+"flags."+f,c.flag(f));y.set(p+"spawn-mobs",c.mobs);y.set(p+"welcome.title",c.text.get("welcome"));y.set(p+"welcome.subtitle",c.text.get("welcome-subtitle"));}try{file.getParentFile().mkdirs();y.save(file);}catch(IOException ex){plugin.getLogger().warning("Guard Claim gagal disimpan: "+ex.getMessage());}}
 private void info(Player p,C c){if(c==null){msg(p,"&cClaim tidak ditemukan.");return;}msg(p,"&b"+c.id+" &7| world &f"+c.worldName+" &7| X &f"+c.x1+".."+c.x2+" &7| Z &f"+c.z1+".."+c.z2);msg(p,"&7Break "+on(c.flag("break"))+" &7Place "+on(c.flag("place"))+" &7PVP "+on(c.flag("pvp"))+" &7Chest "+on(c.flag("chest")));}
 private void help(Player p){for(String x:List.of("&bVeliora Guard Claim","&f/vgclaim pos1 &7dan &f/vgclaim pos2","&f/vgclaim claim <id> &7- area penuh dari bawah sampai atas","&f/vgclaim flags [id] &7- buka GUI flag area","&f/vgclaim flag <id> <flag> <true|false>","&f/vgclaim flag <id> spawn-mobs zombie,skeleton","&f/vgclaim flag <id> welcome <judul>","&f/vgclaim delete <id> confirm"))msg(p,x);}
 private String norm(String s){return switch(s.toLowerCase()){case "doors"->"door";case "iron-doors"->"iron-door";case "trapdoors"->"trapdoor";case "containers"->"chest";case "hostile-spawn"->"spawn";case "passive-spawn"->"passives";default->s.toLowerCase();};}private String clean(String s){if(s==null)return "";return Arrays.stream(s.toLowerCase().split("[,\\s]+" )).map(x->x.replaceAll("[^a-z_]","")).filter(x->!x.isBlank()).distinct().sorted().reduce((a,b)->a+","+b).orElse("");}private String safe(String s){return s==null?"":s.toLowerCase().replaceAll("[^a-z0-9_-]","");}private Boolean bool(String s){return s.equalsIgnoreCase("true")||s.equalsIgnoreCase("on")?true:s.equalsIgnoreCase("false")||s.equalsIgnoreCase("off")?false:null;}private String col(String s){return ChatColor.translateAlternateColorCodes('&',s==null?"":s);}private void msg(Player p,String s){p.sendMessage(col("&8[&aVelioraGuard&8] &r"+s));}private String on(boolean b){return b?"&aTRUE":"&cFALSE";}private String loc(Location l){return l.getBlockX()+", "+l.getBlockY()+", "+l.getBlockZ();}private boolean same(Location a,Location b){return a.getWorld().equals(b.getWorld())&&a.getBlockX()==b.getBlockX()&&a.getBlockY()==b.getBlockY()&&a.getBlockZ()==b.getBlockZ();}
 public List<String> onTabComplete(CommandSender s,Command c,String l,String[] a){if(a.length==1)return List.of("pos1","pos2","claim","delete","flag","flags","list","info","reload");if(a.length==2&&!a[0].equalsIgnoreCase("claim"))return new ArrayList<>(claims.keySet());if(a.length==3&&a[0].equalsIgnoreCase("flag")){List<String>x=new ArrayList<>(F);x.addAll(List.of("spawn-mobs","welcome","welcome-subtitle"));return x;}return a.length==4&&a[0].equalsIgnoreCase("flag")?List.of("true","false"):List.of();}
 private final class H implements InventoryHolder{final C c;final int page;H(C c,int page){this.c=c;this.page=page;}public Inventory getInventory(){return null;}}private static final class C{final String id;final UUID world;final String worldName;final int x1,x2,z1,z2;final Map<String,Boolean>flags=new HashMap<>();final Map<String,String>text=new HashMap<>();String mobs="";C(String i,UUID w,String n,int a,int b,int d,int e){id=i;world=w;worldName=n;x1=a;x2=b;z1=d;z2=e;}static C make(String i,Location a,Location b){return new C(i,a.getWorld().getUID(),a.getWorld().getName(),Math.min(a.getBlockX(),b.getBlockX()),Math.max(a.getBlockX(),b.getBlockX()),Math.min(a.getBlockZ(),b.getBlockZ()),Math.max(a.getBlockZ(),b.getBlockZ()));}boolean flag(String f){return flags.getOrDefault(f,false);}}
}
