package id.velioragardens.veliorasuite.module.actionhouse;

import id.velioragardens.veliorasuite.VelioraSuite;
import org.bukkit.ChatColor;
import org.bukkit.Material;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.inventory.InventoryClickEvent;
import org.bukkit.event.inventory.InventoryCloseEvent;
import org.bukkit.event.inventory.InventoryDragEvent;
import org.bukkit.inventory.Inventory;
import org.bukkit.inventory.InventoryHolder;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.ItemMeta;
import java.text.DecimalFormat;
import java.util.*;

final class ActionHouseGui implements Listener {
    /** Area tengah 7 x 3 seperti screenshot; dipakai untuk market, gudang, dan masukkan barang. */
    private static final int[] GRID = {10,11,12,13,14,15,16,19,20,21,22,23,24,25,28,29,30,31,32,33,34};
    /** Baris chest/chain pada halaman Toko Saya seperti contoh GUI. */
    private static final int[] STORE_SLOTS = {19,20,21,22,23,24,25};
    private static final DecimalFormat MONEY = new DecimalFormat("#,##0.00");
    private final VelioraSuite plugin; private final ActionHouseStore store; private final ActionHouseEconomy economy;
    private final long listingLife; private final double slotCost; private final double shopCost; private final double[] promotionPrices; private final int[] promotionDays;
    ActionHouseGui(VelioraSuite plugin, ActionHouseStore store, ActionHouseEconomy economy, long listingLife, double slotCost, double shopCost, double[] promotionPrices, int[] promotionDays) { this.plugin=plugin; this.store=store; this.economy=economy; this.listingLife=listingLife; this.slotCost=slotCost; this.shopCost=shopCost; this.promotionPrices=promotionPrices; this.promotionDays=promotionDays; }

    void openMarket(Player player, int page) {
        Holder h=new Holder("market", page, null, 0); Inventory inv=plugin.getServer().createInventory(h,54,"§8Veliora Player Shop"); h.inventory=inv; frame(inv);
        List<ActionHouseStore.Listing> all=store.browse(); int from=Math.max(0,page)*GRID.length;
        for(int i=0;i<GRID.length&&from+i<all.size();i++){ActionHouseStore.Listing l=all.get(from+i); ItemStack item=l.item().clone(); ItemMeta meta=item.getItemMeta(); List<String> lore=new ArrayList<>(meta.hasLore()?meta.getLore():List.of()); lore.add("§7Penjual: §f"+l.ownerName()); lore.add("§eHarga: §6$"+MONEY.format(l.price())); lore.add(l.promotedUntil()>System.currentTimeMillis()?"§d★ Dipromosikan":"§7Klik untuk membeli"); meta.setLore(lore); item.setItemMeta(meta); inv.setItem(GRID[i],item); h.ids.put(GRID[i],l.id());}
        if(page>0) inv.setItem(45, icon(Material.ARROW,"§e← Halaman sebelumnya","§7Kembali ke halaman "+page));
        if(from+GRID.length<all.size()) inv.setItem(53,icon(Material.ARROW,"§eHalaman berikutnya →","§7Lihat listing berikutnya"));
        inv.setItem(47,icon(Material.BOOK,"§bPanduan Player Shop","§7Cara jual, beli, promosi, dan klaim uang."));
        inv.setItem(48,icon(Material.BARREL,"§6Gudang kedaluwarsa","§7Ambil barang jualan yang sudah berakhir."));
        inv.setItem(49,icon(Material.BELL,"§eSaldo hasil jual","§7Klaim uang: §6$"+MONEY.format(store.pending(player.getUniqueId()))));
        inv.setItem(50,icon(Material.CHEST,"§aToko saya","§7Kelola slot dan barang yang kamu jual."));
        inv.setItem(51,icon(Material.ENDER_CHEST,"§dPromosikan toko","§7Tampilkan listing lebih atas.")); player.openInventory(inv);
    }
    void openStore(Player player,int page){Holder h=new Holder("store",page,null,0);Inventory inv=plugin.getServer().createInventory(h,54,"§8Toko Saya");h.inventory=inv;frame(inv);boolean hasShop=store.hasShop(player.getUniqueId());int capacity=store.capacity(player.getUniqueId()),from=page*STORE_SLOTS.length;for(int i=0;i<STORE_SLOTS.length;i++){int position=from+i,slot=STORE_SLOTS[i];if(!hasShop||position>=capacity)inv.setItem(slot,icon(Material.CHAIN,"§8Slot terkunci","§7Beli toko atau slot tambahan."));else inv.setItem(slot,icon(Material.CHEST,"§6Slot jual #"+(position+1),"§7Klik untuk menjual item baru."));}if(page>0)inv.setItem(18,icon(Material.ARROW,"§e← Halaman sebelumnya","§7Kembali ke halaman sebelumnya."));if(hasShop&&from+STORE_SLOTS.length<capacity)inv.setItem(26,icon(Material.ARROW,"§eHalaman berikutnya →","§7Lihat slot berikutnya."));if(hasShop){inv.setItem(4,icon(Material.PLAYER_HEAD,"§eToko "+player.getName(),"§7Pemilik toko ini."));int promo=0;for(ActionHouseStore.Listing listing:store.owned(player.getUniqueId()))if(listing.promotedUntil()>System.currentTimeMillis()&&promo<3){inv.setItem(new int[]{2,4,6}[promo++],icon(Material.ENDER_CHEST,"§dIklan aktif","§7Tersisa sampai promosi berakhir."));}}inv.setItem(36,icon(Material.LECTERN,"§bSortir Item","§7Atur urutan barang yang kamu jual."));inv.setItem(38,icon(Material.BARREL,"§6Gudang expired","§7Ambil listing yang telah berakhir."));inv.setItem(40,icon(Material.BELL,"§eSaldo & promosi","§7Klaim hasil jual atau beli iklan."));inv.setItem(42,icon(Material.CHEST,hasShop?"§6Toko "+player.getName():"§eBeli Toko","§7"+(hasShop?"Lihat semua listing aktif.":"Biaya: §6$"+MONEY.format(shopCost))));inv.setItem(44,icon(Material.WRITABLE_BOOK,"§bPanduan lengkap","§7Klik untuk menerima panduan privat."));player.openInventory(inv);}
    void openDraft(Player player){Holder h=new Holder("draft",0,null,100);Inventory inv=plugin.getServer().createInventory(h,54,"§8Jual Barang");h.inventory=inv;frame(inv);for(int slot:GRID)inv.setItem(slot,null);for(int slot=36;slot<=44;slot++)inv.setItem(slot,icon(Material.BLACK_STAINED_GLASS_PANE," "));inv.setItem(37,icon(Material.RED_CONCRETE,"§cBatalkan","§8┃ §7Kembalikan semua item."));inv.setItem(40,icon(Material.ARROW,"§eKembali","§8┃ §7Kembali ke toko."));inv.setItem(42,icon(Material.GOLD_BLOCK,"§eLanjut atur harga","§8┃ §7Buka pengaturan harga."));player.openInventory(inv);}
    void openListings(Player player){Holder h=new Holder("listings",0,null,0);Inventory inv=plugin.getServer().createInventory(h,54,"§8Listing Aktif: "+player.getName());h.inventory=inv;frame(inv);List<ActionHouseStore.Listing> all=store.owned(player.getUniqueId());for(int i=0;i<GRID.length&&i<all.size();i++){ActionHouseStore.Listing l=all.get(i);ItemStack item=l.item().clone();ItemMeta m=item.getItemMeta();m.setLore(List.of("§8━━━━━━━━━━━━━━━━","§7Harga §f: §6$"+MONEY.format(l.price()),"§7Status: "+(l.promotedUntil()>System.currentTimeMillis()?"§dIklan aktif":"§aAktif"),"","§eKlik untuk membatalkan listing","§8━━━━━━━━━━━━━━━━"));item.setItemMeta(m);inv.setItem(GRID[i],item);h.ids.put(GRID[i],l.id());}inv.setItem(49,icon(Material.ARROW,"§eKembali","§8┃ §7Kembali ke toko."));player.openInventory(inv);}
    void openBellMenu(Player player){Holder h=new Holder("bell",0,null,0);Inventory inv=plugin.getServer().createInventory(h,54,"§8Saldo dan Promosi");h.inventory=inv;frame(inv);inv.setItem(22,icon(Material.BELL,"§eSaldo & Promosi","§8┃ §7Pilih layanan di bawah."));inv.setItem(29,icon(Material.HONEY_BLOCK,"§aKlaim hasil penjualan","§8┃ §7Ambil uang hasil penjualan."));inv.setItem(33,icon(Material.ENDER_CHEST,"§dBeli promosi toko","§8┃ §7Naikkan listing ke bagian atas."));inv.setItem(49,icon(Material.ARROW,"§eKembali","§8┃ §7Kembali ke toko."));player.openInventory(inv);}
    void openSort(Player player){Holder h=new Holder("sort",0,null,0);Inventory inv=plugin.getServer().createInventory(h,54,"§8Sortir Listing");h.inventory=inv;frame(inv);inv.setItem(13,icon(Material.BELL,"§eUrutkan barang","§8┃ §7Pilih cara melihat listing."));inv.setItem(31,icon(Material.SUNFLOWER,"§bInfo sortir","§8┃ §7Tidak mengubah harga atau item."));inv.setItem(37,icon(Material.ANVIL,"§fListing terbaru","§8┃ §7Barang terbaru ditampilkan dahulu."));inv.setItem(38,icon(Material.BARRIER,"§cBatal","§8┃ §7Kembali tanpa mengubah urutan."));inv.setItem(40,icon(Material.LECTERN,"§eHarga terendah","§8┃ §7Urutkan dari harga terkecil."));inv.setItem(42,icon(Material.ANVIL,"§6Harga tertinggi","§8┃ §7Urutkan dari harga terbesar."));inv.setItem(43,icon(Material.CHEST,"§dIklan aktif","§8┃ §7Tampilkan barang promosi dahulu."));inv.setItem(49,icon(Material.ARROW,"§eKembali","§8┃ §7Kembali ke toko."));player.openInventory(inv);}
    void openBuy(Player player,String id){ActionHouseStore.Listing l=store.get(id);if(l==null){openMarket(player,0);return;}Holder h=new Holder("buy",0,id,0);Inventory inv=plugin.getServer().createInventory(h,27,"§8Konfirmasi Pembelian");h.inventory=inv;for(int i=0;i<27;i++)inv.setItem(i,filler());inv.setItem(13,l.item());inv.setItem(11,icon(Material.RED_CONCRETE,"§cBatal","§7Kembali ke market."));inv.setItem(15,icon(Material.LIME_CONCRETE,"§aBeli §6$"+MONEY.format(l.price()),"§7Penjual: §f"+l.ownerName()));player.openInventory(inv);}
    void openClaim(Player player){Holder h=new Holder("claim",0,null,0);Inventory inv=plugin.getServer().createInventory(h,54,"§8Klaim Hasil Penjualan");h.inventory=inv;bluePanel(inv);double balance=store.pending(player.getUniqueId());inv.setItem(13,icon(Material.BELL,"§eSaldo tersedia: §6$"+MONEY.format(balance),"§7Uang dari barang yang telah dibeli."));inv.setItem(29,icon(Material.SLIME_BLOCK,"§eAmbil 50%","§7Klaim §6$"+MONEY.format(balance/2D)));inv.setItem(31,icon(Material.SUNFLOWER,"§bTentang saldo","§7Hasil jual disimpan sampai kamu klaim."));inv.setItem(33,icon(Material.HONEY_BLOCK,"§aAmbil semua","§7Klaim §6$"+MONEY.format(balance)));inv.setItem(49,icon(Material.ARROW,"§eKembali","§7Kembali ke Player Shop."));player.openInventory(inv);}
    void openExpired(Player player){Holder h=new Holder("expired",0,null,0);Inventory inv=plugin.getServer().createInventory(h,54,"§8Gudang Barang Kedaluwarsa");h.inventory=inv;frame(inv);List<ItemStack> items=store.expired(player.getUniqueId());for(int i=0;i<GRID.length&&i<items.size();i++){ItemStack item=items.get(i).clone();ItemMeta m=item.getItemMeta();m.setLore(List.of("§eKlik untuk mengambil kembali barang ini."));item.setItemMeta(m);inv.setItem(GRID[i],item);h.indices.put(GRID[i],i);}inv.setItem(49,icon(Material.ARROW,"§eKembali","§7Kembali ke Player Shop."));player.openInventory(inv);}
    void openPromo(Player player){Holder h=new Holder("promo",0,null,0);Inventory inv=plugin.getServer().createInventory(h,54,"§8Promosikan Toko");h.inventory=inv;bluePanel(inv);inv.setItem(13,icon(Material.BELL,"§dPromosi listing","§7Listing diprioritaskan di bagian atas market."));promo(inv,29,Material.COPPER_INGOT,promotionDays[0]+" hari",promotionPrices[0],promotionDays[0]);promo(inv,30,Material.IRON_INGOT,promotionDays[1]+" hari",promotionPrices[1],promotionDays[1]);promo(inv,31,Material.GOLD_INGOT,promotionDays[2]+" hari",promotionPrices[2],promotionDays[2]);promo(inv,32,Material.DIAMOND,promotionDays[3]+" hari",promotionPrices[3],promotionDays[3]);promo(inv,33,Material.NETHERITE_INGOT,promotionDays[4]+" hari",promotionPrices[4],promotionDays[4]);inv.setItem(49,icon(Material.ARROW,"§eKembali","§7Kembali ke Player Shop."));player.openInventory(inv);}
    private void openPrice(Player player,Holder draft){draft.preserve=true;Holder h=new Holder("price",0,null,draft.price);h.parent=draft;Inventory inv=plugin.getServer().createInventory(h,54,"§8Atur Harga Barang");h.inventory=inv;frame(inv);for(int slot:GRID)inv.setItem(slot,icon(Material.BLUE_STAINED_GLASS_PANE," "));for(int slot=37;slot<=43;slot++)inv.setItem(slot,icon(Material.RED_STAINED_GLASS_PANE," "));int[] plus={5,10,20,30,40,50};for(int i=0;i<plus.length;i++){inv.setItem(28+i,icon(Material.LIGHT_BLUE_STAINED_GLASS_PANE,"§b+ $"+plus[i],"§7Tambah harga."));inv.setItem(37+i,icon(Material.RED_STAINED_GLASS_PANE,"§c- $"+plus[i],"§7Kurangi harga."));}inv.setItem(13,icon(Material.BELL,"§eHarga: §6$"+MONEY.format(draft.price),"§7Pilih nominal di bawah."));inv.setItem(49,icon(Material.ARROW,"§eKembali","§7Simpan harga dan kembali."));player.openInventory(inv);}
    private void promo(Inventory inv,int slot,Material material,String label,double price,int days){inv.setItem(slot,icon(material,"§dPromosi "+label,"§7Biaya: §6$"+MONEY.format(price),"§7Tampilkan semua listing kamu lebih atas."));}
    @EventHandler public void click(InventoryClickEvent e){if(!(e.getWhoClicked() instanceof Player p)||!(e.getView().getTopInventory().getHolder() instanceof Holder h))return;int raw=e.getRawSlot();boolean top=e.getClickedInventory()!=null&&e.getClickedInventory().equals(e.getView().getTopInventory());if(!top){if(!h.type.equals("draft"))e.setCancelled(true);return;}if(h.type.equals("draft")&&contains(GRID,raw))return;e.setCancelled(true);if(raw<0)return;switch(h.type){case "market"->marketClick(p,h,raw);case "store"->storeClick(p,h,raw);case "listings"->listingsClick(p,h,raw);case "bell"->bellClick(p,raw);case "sort"->sortClick(p,raw);case "draft"->draftClick(p,h,raw);case "price"->priceClick(p,h,raw);case "buy"->buyClick(p,h,raw);case "claim"->claimClick(p,raw);case "expired"->expiredClick(p,h,raw);case "promo"->promoClick(p,raw);}}
    @EventHandler public void drag(InventoryDragEvent e){if(e.getView().getTopInventory().getHolder() instanceof Holder h){if(!h.type.equals("draft")||e.getRawSlots().stream().anyMatch(slot->!contains(GRID,slot)))e.setCancelled(true);}}
    @EventHandler public void close(InventoryCloseEvent e){if(!(e.getInventory().getHolder() instanceof Holder h))return;if(h.type.equals("draft")&&!h.preserve)returnDraft((Player)e.getPlayer(),h);if(h.type.equals("price")&&h.parent!=null&&!h.preserve)returnDraft((Player)e.getPlayer(),h.parent);}
    private void marketClick(Player p,Holder h,int slot){if(slot==45&&h.page>0)openMarket(p,h.page-1);else if(slot==53)openMarket(p,h.page+1);else if(slot==47)guide(p);else if(slot==48)openExpired(p);else if(slot==49)openClaim(p);else if(slot==50)openStore(p,0);else if(slot==51)openPromo(p);else if(h.ids.containsKey(slot))openBuy(p,h.ids.get(slot));}
    private void storeClick(Player p,Holder h,int slot){if(slot==18&&h.page>0)openStore(p,h.page-1);else if(slot==26)openStore(p,h.page+1);else if(slot==36)openSort(p);else if(slot==44)guide(p);else if(slot==38)openExpired(p);else if(slot==40)openBellMenu(p);else if(slot==42){if(store.hasShop(p.getUniqueId()))openListings(p);else buyShop(p);}else if(slot==2||slot==4||slot==6)openPromo(p);else if(contains(STORE_SLOTS,slot)){int position=h.page*STORE_SLOTS.length+index(STORE_SLOTS,slot);if(!store.hasShop(p.getUniqueId()))return;if(position>=store.capacity(p.getUniqueId()))buySlot(p,h.page);else openDraft(p);}}
    private void listingsClick(Player p,Holder h,int slot){if(slot==49){openStore(p,0);return;}String id=h.ids.get(slot);if(id==null)return;ActionHouseStore.Listing listing=store.get(id);if(listing!=null){store.remove(id);give(p,listing.item());p.sendMessage("§aListing dibatalkan dan item dikembalikan.");openListings(p);}}
    private void bellClick(Player p,int slot){if(slot==29)openClaim(p);else if(slot==33)openPromo(p);else if(slot==49)openStore(p,0);}
    private void sortClick(Player p,int slot){if(slot==38||slot==49){openStore(p,0);return;}if(slot==37||slot==40||slot==42||slot==43)openListings(p);}
    private void buyShop(Player p){ActionHouseEconomy.Result result=economy.withdraw(p,shopCost);if(result==ActionHouseEconomy.Result.OK){store.buyShop(p.getUniqueId());p.sendMessage("§aToko kamu berhasil dibeli. Selamat berjualan!");openStore(p,0);}else p.sendMessage(result==ActionHouseEconomy.Result.INSUFFICIENT?"§cUang kamu tidak cukup untuk membeli toko.":"§cEkonomi Vault belum siap; toko tidak dibeli.");}
    private void buySlot(Player p,int page){ActionHouseEconomy.Result r=economy.withdraw(p,slotCost);if(r==ActionHouseEconomy.Result.OK){store.addSlot(p.getUniqueId());p.sendMessage("§aSlot toko baru berhasil dibeli.");openStore(p,page);}else p.sendMessage(r==ActionHouseEconomy.Result.INSUFFICIENT?"§cUang kamu tidak cukup.":"§cEkonomi Vault belum tersedia; slot tidak dibeli.");}
    private void draftClick(Player p,Holder h,int slot){if(slot==40){p.closeInventory();openStore(p,0);return;}if(slot==37){p.closeInventory();return;}if(slot==42)openPrice(p,h);}
    private void priceClick(Player p,Holder h,int slot){if(h.parent==null)return;int[] values={5,10,20,30,40,50};for(int i=0;i<values.length;i++){if(slot==28+i)h.parent.price+=values[i];if(slot==37+i)h.parent.price=Math.max(1,h.parent.price-values[i]);}if(slot==49){h.preserve=true;finishDraft(p,h.parent);return;}h.inventory.setItem(13,icon(Material.BELL,"§eHarga: §6$"+MONEY.format(h.parent.price),"§7Pilih nominal di bawah."));}
    private void finishDraft(Player p,Holder draft){List<ItemStack> items=new ArrayList<>();for(int slot:GRID){ItemStack item=draft.inventory.getItem(slot);if(item!=null&&!item.getType().isAir())items.add(item.clone());}int available=store.capacity(p.getUniqueId())-store.owned(p.getUniqueId()).size();if(items.isEmpty()){p.sendMessage("§cMasukkan minimal satu item sebelum menetapkan harga.");draft.preserve=false;p.openInventory(draft.inventory);return;}if(items.size()>available){p.sendMessage("§cSlot toko tidak cukup. Tersedia: "+available);draft.preserve=false;p.openInventory(draft.inventory);return;}for(int slot:GRID)draft.inventory.setItem(slot,null);draft.preserve=true;for(ItemStack item:items)store.add(p.getUniqueId(),p.getName(),item,draft.price,listingLife);p.sendMessage("§aListing berhasil dibuat dengan harga §6$"+MONEY.format(draft.price)+" §aper item.");p.closeInventory();}
    private void buyClick(Player p,Holder h,int slot){if(slot==11){openMarket(p,0);return;}if(slot!=15)return;ActionHouseStore.Listing l=store.get(h.id);if(l==null){p.sendMessage("§cListing ini sudah tidak tersedia.");openMarket(p,0);return;}if(l.owner().equals(p.getUniqueId())){p.sendMessage("§cKamu tidak bisa membeli barang sendiri.");return;}ActionHouseEconomy.Result result=economy.withdraw(p,l.price());if(result!=ActionHouseEconomy.Result.OK){p.sendMessage(result==ActionHouseEconomy.Result.INSUFFICIENT?"§cUang kamu tidak cukup.":"§cEkonomi Vault belum siap; pembelian dibatalkan.");return;}store.remove(l.id());store.addPending(l.owner(),l.price());give(p,l.item());p.sendMessage("§aPembelian berhasil. Barang telah masuk ke inventori.");Player owner=plugin.getServer().getPlayer(l.owner());if(owner!=null)owner.sendMessage("§eBarang di toko kamu terjual: §6$"+MONEY.format(l.price()));openMarket(p,0);}
    private void claimClick(Player p,int slot){double balance=store.pending(p.getUniqueId());double amount=slot==33?balance:slot==29?balance/2D:0;if(slot==49){openMarket(p,0);return;}if(amount<=0)return;ActionHouseEconomy.Result r=economy.deposit(p,amount);if(r==ActionHouseEconomy.Result.OK){store.reducePending(p.getUniqueId(),amount);p.sendMessage("§aBerhasil mengklaim §6$"+MONEY.format(amount));openClaim(p);}else p.sendMessage("§cEkonomi Vault belum siap; saldo tetap aman.");}
    private void expiredClick(Player p,Holder h,int slot){if(slot==49){openMarket(p,0);return;}Integer i=h.indices.get(slot);if(i==null)return;ItemStack item=store.takeExpired(p.getUniqueId(),i);if(item!=null){give(p,item);p.sendMessage("§aBarang dikembalikan ke inventori.");openExpired(p);}}
    private void promoClick(Player p,int slot){if(slot==49){openMarket(p,0);return;}int[] target={29,30,31,32,33};for(int i=0;i<target.length;i++)if(slot==target[i]){if(store.owned(p.getUniqueId()).isEmpty()){p.sendMessage("§cKamu belum punya listing untuk dipromosikan.");return;}ActionHouseEconomy.Result r=economy.withdraw(p,promotionPrices[i]);if(r==ActionHouseEconomy.Result.OK){store.promote(p.getUniqueId(),System.currentTimeMillis()+promotionDays[i]*86400000L);p.sendMessage("§dPromosi toko aktif selama "+promotionDays[i]+" hari.");openPromo(p);}else p.sendMessage(r==ActionHouseEconomy.Result.INSUFFICIENT?"§cUang kamu tidak cukup.":"§cEkonomi Vault belum siap.");}}
    private void guide(Player p){p.closeInventory();p.sendMessage("§b§lPLAYER SHOP §7• §fJual barang dari §aToko Saya§f, klik item market untuk membeli. §dPromosi§f menaikkan urutan listing; hasil jual masuk §eSaldo§f. Barang yang kedaluwarsa aman di §6Barrel§f.");}
    private void frame(Inventory inv){for(int i=0;i<54;i++)inv.setItem(i,filler());}
    private void bluePanel(Inventory inv){frame(inv);for(int slot:GRID)inv.setItem(slot,icon(Material.LIGHT_BLUE_STAINED_GLASS_PANE," "));}
    private ItemStack filler(){return icon(Material.GRAY_STAINED_GLASS_PANE," ");}
    private ItemStack icon(Material type,String name,String... lore){ItemStack item=new ItemStack(type);ItemMeta meta=item.getItemMeta();meta.setDisplayName(name);if(lore.length>0)meta.setLore(Arrays.asList(lore));item.setItemMeta(meta);return item;}
    private void give(Player p,ItemStack item){for(ItemStack left:p.getInventory().addItem(item).values())p.getWorld().dropItemNaturally(p.getLocation(),left);}
    private void returnDraft(Player player,Holder draft){for(int slot:GRID){ItemStack item=draft.inventory.getItem(slot);if(item!=null&&!item.getType().isAir()){draft.inventory.setItem(slot,null);give(player,item);}}}
    private static boolean contains(int[] arr,int value){for(int x:arr)if(x==value)return true;return false;}private static int index(int[] a,int v){for(int i=0;i<a.length;i++)if(a[i]==v)return i;return -1;}
    private static final class Holder implements InventoryHolder {final String type;final int page;final String id;final Map<Integer,String> ids=new HashMap<>();final Map<Integer,Integer> indices=new HashMap<>();double price;Inventory inventory;Holder parent;boolean preserve;Holder(String type,int page,String id,double price){this.type=type;this.page=page;this.id=id;this.price=price;}public Inventory getInventory(){return inventory;}}
}
