package id.velioragardens.veliorasuite.module.actionhouse;

import id.velioragardens.veliorasuite.VelioraSuite;
import org.bukkit.ChatColor;
import org.bukkit.Material;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.inventory.InventoryClickEvent;
import org.bukkit.event.inventory.InventoryCloseEvent;
import org.bukkit.event.inventory.InventoryDragEvent;
import org.bukkit.inventory.Inventory;
import org.bukkit.inventory.InventoryHolder;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.ItemMeta;
import java.text.DecimalFormat;
import java.util.*;

final class ActionHouseGui implements Listener {
    private static final int[] GRID = {10,11,12,13,14,15,16,19,20,21,22,23,24,25,28,29,30,31,32,33,34};
    private static final DecimalFormat MONEY = new DecimalFormat("#,##0.00");
    private final VelioraSuite plugin; private final ActionHouseStore store; private final ActionHouseEconomy economy;
    private final long listingLife; private final double slotCost;
    ActionHouseGui(VelioraSuite plugin, ActionHouseStore store, ActionHouseEconomy economy, long listingLife, double slotCost) { this.plugin=plugin; this.store=store; this.economy=economy; this.listingLife=listingLife; this.slotCost=slotCost; }

    void openMarket(Player player, int page) {
        Holder h=new Holder("market", page, null, 0); Inventory inv=plugin.getServer().createInventory(h,54,"§8Veliora Player Shop"); h.inventory=inv; frame(inv);
        List<ActionHouseStore.Listing> all=store.browse(); int from=Math.max(0,page)*GRID.length;
        for(int i=0;i<GRID.length&&from+i<all.size();i++){ActionHouseStore.Listing l=all.get(from+i); ItemStack item=l.item().clone(); ItemMeta meta=item.getItemMeta(); List<String> lore=new ArrayList<>(meta.hasLore()?meta.getLore():List.of()); lore.add("§7Penjual: §f"+l.ownerName()); lore.add("§eHarga: §6$"+MONEY.format(l.price())); lore.add(l.promotedUntil()>System.currentTimeMillis()?"§d★ Dipromosikan":"§7Klik untuk membeli"); meta.setLore(lore); item.setItemMeta(meta); inv.setItem(GRID[i],item); h.ids.put(GRID[i],l.id());}
        if(page>0) inv.setItem(45, icon(Material.ARROW,"§e← Halaman sebelumnya","§7Kembali ke halaman "+page));
        if(from+GRID.length<all.size()) inv.setItem(53,icon(Material.ARROW,"§eHalaman berikutnya →","§7Lihat listing berikutnya"));
        inv.setItem(47,icon(Material.BOOK,"§bPanduan Player Shop","§7Cara jual, beli, promosi, dan klaim uang."));
        inv.setItem(48,icon(Material.BARREL,"§6Gudang kedaluwarsa","§7Ambil barang jualan yang sudah berakhir."));
        inv.setItem(49,icon(Material.BELL,"§eSaldo hasil jual","§7Klaim uang: §6$"+MONEY.format(store.pending(player.getUniqueId()))));
        inv.setItem(50,icon(Material.CHEST,"§aToko saya","§7Kelola slot dan barang yang kamu jual."));
        inv.setItem(51,icon(Material.ENDER_CHEST,"§dPromosikan toko","§7Tampilkan listing lebih atas.")); player.openInventory(inv);
    }
    void openStore(Player player,int page){Holder h=new Holder("store",page,null,0);Inventory inv=plugin.getServer().createInventory(h,54,"§8Toko Saya");h.inventory=inv;frame(inv);List<ActionHouseStore.Listing> all=store.owned(player.getUniqueId());int from=page*GRID.length;int capacity=store.capacity(player.getUniqueId()); for(int i=0;i<GRID.length;i++){if(i+from<all.size()){ActionHouseStore.Listing l=all.get(i+from);ItemStack item=l.item().clone();ItemMeta meta=item.getItemMeta();meta.setLore(List.of("§eHarga: §6$"+MONEY.format(l.price()),"§7Klik untuk batalkan listing."));item.setItemMeta(meta);inv.setItem(GRID[i],item);h.ids.put(GRID[i],l.id());}else if(i+from<capacity)inv.setItem(GRID[i],icon(Material.CHEST,"§aSlot tersedia","§7Klik untuk menaruh barang jualan baru."));else inv.setItem(GRID[i],icon(Material.CHAIN,"§8Slot terkunci","§7Klik untuk membeli slot seharga §6$"+MONEY.format(slotCost)));}if(page>0)inv.setItem(45,icon(Material.ARROW,"§e← Sebelumnya","§7Halaman sebelumnya"));if(from+GRID.length<Math.max(all.size(),capacity))inv.setItem(53,icon(Material.ARROW,"§eBerikutnya →","§7Halaman berikutnya"));inv.setItem(47,icon(Material.BOOK,"§bPanduan","§7Buka chat panduan."));inv.setItem(48,icon(Material.BARREL,"§6Gudang kedaluwarsa","§7Barang lama yang belum terjual."));inv.setItem(49,icon(Material.BELL,"§eKlaim hasil jual","§6$"+MONEY.format(store.pending(player.getUniqueId()))));inv.setItem(50,icon(Material.LIME_DYE,"§aJual barang baru","§7Masukkan barang, atur harga, lalu konfirmasi."));inv.setItem(51,icon(Material.ENDER_CHEST,"§dPromosi toko","§7Naikkan listing ke bagian atas."));player.openInventory(inv);}
    void openDraft(Player player){Holder h=new Holder("draft",0,null,100);Inventory inv=plugin.getServer().createInventory(h,54,"§8Jual Barang");h.inventory=inv;frame(inv);for(int slot:GRID)inv.setItem(slot,null);inv.setItem(4,icon(Material.BELL,"§eHarga per item: §6$100.00","§7Klik kontrol + / - di bawah."));inv.setItem(45,icon(Material.RED_STAINED_GLASS_PANE,"§cBatalkan","§7Kembalikan semua barang."));inv.setItem(47,icon(Material.REDSTONE,"§c- 10","§7Kurangi harga"));inv.setItem(48,icon(Material.REDSTONE,"§c- 1","§7Kurangi harga"));inv.setItem(49,icon(Material.ARROW,"§eKembali","§7Kembali ke toko saya."));inv.setItem(50,icon(Material.GLOWSTONE_DUST,"§a+ 1","§7Tambah harga"));inv.setItem(51,icon(Material.GLOWSTONE,"§a+ 10","§7Tambah harga"));inv.setItem(53,icon(Material.GOLD_BLOCK,"§eKonfirmasi jual","§7Buat listing dengan harga saat ini."));player.openInventory(inv);}
    void openBuy(Player player,String id){ActionHouseStore.Listing l=store.get(id);if(l==null){openMarket(player,0);return;}Holder h=new Holder("buy",0,id,0);Inventory inv=plugin.getServer().createInventory(h,27,"§8Konfirmasi Pembelian");h.inventory=inv;for(int i=0;i<27;i++)inv.setItem(i,filler());inv.setItem(13,l.item());inv.setItem(11,icon(Material.RED_CONCRETE,"§cBatal","§7Kembali ke market."));inv.setItem(15,icon(Material.LIME_CONCRETE,"§aBeli §6$"+MONEY.format(l.price()),"§7Penjual: §f"+l.ownerName()));player.openInventory(inv);}
    void openClaim(Player player){Holder h=new Holder("claim",0,null,0);Inventory inv=plugin.getServer().createInventory(h,54,"§8Klaim Hasil Penjualan");h.inventory=inv;frame(inv);double balance=store.pending(player.getUniqueId());inv.setItem(4,icon(Material.BELL,"§eSaldo tersedia: §6$"+MONEY.format(balance),"§7Uang dari barang yang telah dibeli."));inv.setItem(22,icon(Material.SUNFLOWER,"§bTentang saldo penjualan","§7Hasil jual disimpan aman sampai kamu klaim."));inv.setItem(30,icon(Material.HONEY_BLOCK,"§aAmbil semua","§7Klaim §6$"+MONEY.format(balance)));inv.setItem(32,icon(Material.SLIME_BLOCK,"§eAmbil 50%","§7Klaim §6$"+MONEY.format(balance/2D)));inv.setItem(49,icon(Material.ARROW,"§eKembali","§7Kembali ke Player Shop."));player.openInventory(inv);}
    void openExpired(Player player){Holder h=new Holder("expired",0,null,0);Inventory inv=plugin.getServer().createInventory(h,54,"§8Gudang Barang Kedaluwarsa");h.inventory=inv;frame(inv);List<ItemStack> items=store.expired(player.getUniqueId());for(int i=0;i<GRID.length&&i<items.size();i++){ItemStack item=items.get(i).clone();ItemMeta m=item.getItemMeta();m.setLore(List.of("§eKlik untuk mengambil kembali barang ini."));item.setItemMeta(m);inv.setItem(GRID[i],item);h.indices.put(GRID[i],i);}inv.setItem(49,icon(Material.ARROW,"§eKembali","§7Kembali ke Player Shop."));player.openInventory(inv);}
    void openPromo(Player player){Holder h=new Holder("promo",0,null,0);Inventory inv=plugin.getServer().createInventory(h,54,"§8Promosikan Toko");h.inventory=inv;frame(inv);inv.setItem(4,icon(Material.BELL,"§dPromosi listing","§7Listing diprioritaskan di bagian atas market."));promo(inv,20,Material.COPPER_INGOT,"1 hari",5000,1);promo(inv,22,Material.IRON_INGOT,"3 hari",12000,3);promo(inv,24,Material.GOLD_INGOT,"7 hari",25000,7);promo(inv,31,Material.DIAMOND,"14 hari",50000,14);promo(inv,49,Material.ARROW,"Kembali",0,0);player.openInventory(inv);}
    private void promo(Inventory inv,int slot,Material material,String label,double price,int days){inv.setItem(slot,icon(material,"§dPromosi "+label,"§7Biaya: §6$"+MONEY.format(price),"§7Tampilkan semua listing kamu lebih atas."));}
    @EventHandler public void click(InventoryClickEvent e){if(!(e.getWhoClicked() instanceof Player p)||!(e.getView().getTopInventory().getHolder() instanceof Holder h))return;int raw=e.getRawSlot();boolean top=e.getClickedInventory()!=null&&e.getClickedInventory().equals(e.getView().getTopInventory());if(!top){if(!h.type.equals("draft"))e.setCancelled(true);return;}if(h.type.equals("draft")&&contains(GRID,raw))return;e.setCancelled(true);if(raw<0)return;switch(h.type){case "market"->marketClick(p,h,raw);case "store"->storeClick(p,h,raw);case "draft"->draftClick(p,h,raw);case "buy"->buyClick(p,h,raw);case "claim"->claimClick(p,raw);case "expired"->expiredClick(p,h,raw);case "promo"->promoClick(p,raw);}}
    @EventHandler public void drag(InventoryDragEvent e){if(e.getView().getTopInventory().getHolder() instanceof Holder h){if(!h.type.equals("draft")||e.getRawSlots().stream().anyMatch(slot->!contains(GRID,slot)))e.setCancelled(true);}}
    @EventHandler public void close(InventoryCloseEvent e){if(e.getInventory().getHolder() instanceof Holder h&&h.type.equals("draft")){for(int slot:GRID){ItemStack item=e.getInventory().getItem(slot);if(item!=null&&!item.getType().isAir())give((Player)e.getPlayer(),item);}}}
    private void marketClick(Player p,Holder h,int slot){if(slot==45&&h.page>0)openMarket(p,h.page-1);else if(slot==53)openMarket(p,h.page+1);else if(slot==47)guide(p);else if(slot==48)openExpired(p);else if(slot==49)openClaim(p);else if(slot==50)openStore(p,0);else if(slot==51)openPromo(p);else if(h.ids.containsKey(slot))openBuy(p,h.ids.get(slot));}
    private void storeClick(Player p,Holder h,int slot){if(slot==45&&h.page>0)openStore(p,h.page-1);else if(slot==53)openStore(p,h.page+1);else if(slot==47)guide(p);else if(slot==48)openExpired(p);else if(slot==49)openClaim(p);else if(slot==50)openDraft(p);else if(slot==51)openPromo(p);else if(h.ids.containsKey(slot)){ActionHouseStore.Listing l=store.get(h.ids.get(slot));if(l!=null){store.remove(l.id());give(p,l.item());p.sendMessage("§aListing dibatalkan; barang dikembalikan.");openStore(p,h.page);}}else if(contains(GRID,slot)){int position=h.page*GRID.length+index(GRID,slot);if(position>=store.capacity(p.getUniqueId()))buySlot(p,h.page);else openDraft(p);}}
    private void buySlot(Player p,int page){ActionHouseEconomy.Result r=economy.withdraw(p,slotCost);if(r==ActionHouseEconomy.Result.OK){store.addSlot(p.getUniqueId());p.sendMessage("§aSlot toko baru berhasil dibeli.");openStore(p,page);}else p.sendMessage(r==ActionHouseEconomy.Result.INSUFFICIENT?"§cUang kamu tidak cukup.":"§cEkonomi Vault belum tersedia; slot tidak dibeli.");}
    private void draftClick(Player p,Holder h,int slot){if(slot==47)h.price=Math.max(1,h.price-10);else if(slot==48)h.price=Math.max(1,h.price-1);else if(slot==50)h.price+=1;else if(slot==51)h.price+=10;else if(slot==49){p.closeInventory();openStore(p,0);return;}else if(slot==45){p.closeInventory();return;}else if(slot==53){List<ItemStack> items=new ArrayList<>();for(int s:GRID){ItemStack i=h.inventory.getItem(s);if(i!=null&&!i.getType().isAir())items.add(i.clone());}int available=store.capacity(p.getUniqueId())-store.owned(p.getUniqueId()).size();if(items.isEmpty()){p.sendMessage("§cMasukkan minimal satu barang.");return;}if(items.size()>available){p.sendMessage("§cSlot toko tidak cukup. Tersedia: "+available);return;}for(int s:GRID)h.inventory.setItem(s,null);for(ItemStack i:items)store.add(p.getUniqueId(),p.getName(),i,h.price,listingLife);p.sendMessage("§a"+items.size()+" barang berhasil dijual seharga §6$"+MONEY.format(h.price)+" §aper item.");p.closeInventory();return;}h.inventory.setItem(4,icon(Material.BELL,"§eHarga per item: §6$"+MONEY.format(h.price),"§7Klik kontrol + / - di bawah."));}
    private void buyClick(Player p,Holder h,int slot){if(slot==11){openMarket(p,0);return;}if(slot!=15)return;ActionHouseStore.Listing l=store.get(h.id);if(l==null){p.sendMessage("§cListing ini sudah tidak tersedia.");openMarket(p,0);return;}if(l.owner().equals(p.getUniqueId())){p.sendMessage("§cKamu tidak bisa membeli barang sendiri.");return;}ActionHouseEconomy.Result result=economy.withdraw(p,l.price());if(result!=ActionHouseEconomy.Result.OK){p.sendMessage(result==ActionHouseEconomy.Result.INSUFFICIENT?"§cUang kamu tidak cukup.":"§cEkonomi Vault belum siap; pembelian dibatalkan.");return;}store.remove(l.id());store.addPending(l.owner(),l.price());give(p,l.item());p.sendMessage("§aPembelian berhasil. Barang telah masuk ke inventori.");Player owner=plugin.getServer().getPlayer(l.owner());if(owner!=null)owner.sendMessage("§eBarang di toko kamu terjual: §6$"+MONEY.format(l.price()));openMarket(p,0);}
    private void claimClick(Player p,int slot){double balance=store.pending(p.getUniqueId());double amount=slot==30?balance:slot==32?balance/2D:0;if(slot==49){openMarket(p,0);return;}if(amount<=0)return;ActionHouseEconomy.Result r=economy.deposit(p,amount);if(r==ActionHouseEconomy.Result.OK){store.reducePending(p.getUniqueId(),amount);p.sendMessage("§aBerhasil mengklaim §6$"+MONEY.format(amount));openClaim(p);}else p.sendMessage("§cEkonomi Vault belum siap; saldo tetap aman.");}
    private void expiredClick(Player p,Holder h,int slot){if(slot==49){openMarket(p,0);return;}Integer i=h.indices.get(slot);if(i==null)return;ItemStack item=store.takeExpired(p.getUniqueId(),i);if(item!=null){give(p,item);p.sendMessage("§aBarang dikembalikan ke inventori.");openExpired(p);}}
    private void promoClick(Player p,int slot){if(slot==49){openMarket(p,0);return;}int[] target={20,22,24,31};double[] prices={5000,12000,25000,50000};int[] days={1,3,7,14};for(int i=0;i<target.length;i++)if(slot==target[i]){if(store.owned(p.getUniqueId()).isEmpty()){p.sendMessage("§cKamu belum punya listing untuk dipromosikan.");return;}ActionHouseEconomy.Result r=economy.withdraw(p,prices[i]);if(r==ActionHouseEconomy.Result.OK){store.promote(p.getUniqueId(),System.currentTimeMillis()+days[i]*86400000L);p.sendMessage("§dPromosi toko aktif selama "+days[i]+" hari.");openPromo(p);}else p.sendMessage(r==ActionHouseEconomy.Result.INSUFFICIENT?"§cUang kamu tidak cukup.":"§cEkonomi Vault belum siap.");}}
    private void guide(Player p){p.closeInventory();p.sendMessage("§b§lPLAYER SHOP §7• §fJual barang dari §aToko Saya§f, klik item market untuk membeli. §dPromosi§f menaikkan urutan listing; hasil jual masuk §eSaldo§f. Barang yang kedaluwarsa aman di §6Barrel§f.");}
    private void frame(Inventory inv){for(int i=0;i<54;i++)if(!contains(GRID,i))inv.setItem(i,filler());}
    private ItemStack filler(){return icon(Material.GRAY_STAINED_GLASS_PANE," ");}
    private ItemStack icon(Material type,String name,String... lore){ItemStack item=new ItemStack(type);ItemMeta meta=item.getItemMeta();meta.setDisplayName(name);if(lore.length>0)meta.setLore(Arrays.asList(lore));item.setItemMeta(meta);return item;}
    private void give(Player p,ItemStack item){for(ItemStack left:p.getInventory().addItem(item).values())p.getWorld().dropItemNaturally(p.getLocation(),left);}
    private static boolean contains(int[] arr,int value){for(int x:arr)if(x==value)return true;return false;}private static int index(int[] a,int v){for(int i=0;i<a.length;i++)if(a[i]==v)return i;return -1;}
    private static final class Holder implements InventoryHolder {final String type;final int page;final String id;final Map<Integer,String> ids=new HashMap<>();final Map<Integer,Integer> indices=new HashMap<>();double price;Inventory inventory;Holder(String type,int page,String id,double price){this.type=type;this.page=page;this.id=id;this.price=price;}public Inventory getInventory(){return inventory;}}
}
